### ISSUE TITLE
projectgenerator is not using the lastest version of ili2c

### ISSUE THREAD

**Issue by juusechec** [AgenciaImplementacion/projectgenerator#2]
The current version of ili2db has a bug that prevents to use https repositories. In ili2c version 4.7.7 (2018-02-08) this problem was resolved.
https://github.com/claeis/ili2c/issues/9

**Comment by gacarrillor** [comment]
Project Generator doesn't use the latest version of ili2pg. Do you know if using that one fix this issue?

**Comment by juusechec** [comment]
The latest version published in http://www.eisenhutinformatik.ch/interlis/ili2pg/ is ili2pg-3.11.2, the changelog https://github.com/claeis/ili2db/commit/777b0c0a88c82d2467755d4edd524107e6a8f7a5 is showing that is using ili2c-4.7.7.

**Comment by gacarrillor** [comment]
Should be fixed with https://github.com/opengisch/projectgenerator/pull/148

**Comment by gacarrillor** [comment]
Done! https://github.com/opengisch/projectgenerator/pull/148

**Comment by juusechec** [comment]
Tnks
