### ISSUE TITLE
Generate tests to

### ISSUE THREAD

**Issue by juusechec** [AgenciaImplementacion/projectgenerator#4]
- [x] probe generate with geopackage and postgres without postgis
- [x] pg without schema
- [x] pg/gpkg with scheme but without tables
- [x] with tables, but not with interlis definition tables (no metadata tables pushed in ili2db generate database)

(create object Generator and create layers verifying integrity of data https://github.com/AgenciaImplementacion/projectgenerator/blob/b8cb322cc4ef1e01fecbf642ce3cc1f1db396ac5/projectgenerator/gui/generate_project.py#L240)
Releated with issue https://github.com/opengisch/projectgenerator/issues/155
Please, push changes in branch https://github.com/opengisch/projectgenerator/pull/157

**Comment by gacarrillor** [comment]
Thank you Jorge!
